---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    cluster.ocs.openshift.io/local-devices: 'true'
    storagesystem.odf.openshift.io/watched-by: ocs-storagecluster-storagesystem
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
  finalizers:
    - storagecluster.ocs.openshift.io
spec:
  storageDeviceSets:
    - config: {}
      count: 3
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: lso
          volumeMode: Block
        status: {}
      name: ocs-deviceset-lso
      placement: {}
      preparePlacement: {}
      replica: 1
      resources: {}
  encryption:
    kms: {}
  mirroring: {}
  monDataDirHostPath: /var/lib/rook
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  arbiter: {}
  nodeTopologies: {}
  externalStorage: {}
  #version: 4.9.0
  flexibleScaling: true
  # https://access.redhat.com/articles/6408481
  placement:
    all:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    mds:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    noobaa-core:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
    rgw:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        operator: Equal
        value: "reserved"
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
