---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhacm-operator.yml
  - rhacm-instance.yml
  - local-storage-operator.yml
  - lso-config.yml
  - odf-operator.yml
  - odf-config.yml
  - loki-operator.yml
  - netobserv-operator.yml
