apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
    - group: "v1"
      kind: "Namespace"
      jsonPointers:
        - /metadata/labels
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - kustomize:
        version: v5.1.0
      repoURL: 'https://github.com/kenmoini/rhacm-config-for-rhacs.git'
      targetRevision: main
      ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
      path: rhacm-config/placement-bindings/
    - kustomize:
        version: v5.1.0
      repoURL: 'https://github.com/kenmoini/rhacm-config-for-rhacs.git'
      targetRevision: main
      ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
      path: rhacm-config/placement-rules/
    - kustomize:
        version: v5.1.0
      repoURL: 'https://github.com/kenmoini/rhacm-config-for-rhacs.git'
      targetRevision: main
      ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
      path: rhacm-config/policies/
    - kustomize:
        version: v5.1.0
      repoURL: 'https://github.com/kenmoini/ocp4-security-demo.git'
      targetRevision: main
      ## Path is the repo directory that containers the cluster(s) configuration and deployment manifests
      path: manifests/rhacm/config/
  project: local-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true
      # selfHeal: false # overrides changes made on the cluster that drift from git state